### ISSUE TITLE
Provide minor mode

### ISSUE THREAD

**Issue by theldoria** [hatheroldev/mc-calc#3]
This package has some global and buffer local state, that is not easily visible to the user.
If you used `mc-calc-grab` in buffer `a` then a global state changed in which a subsequent call to `mc-calc-copy-to-buffer` will return to `a` and insert the calc top element. It would be nice to see:
- in buffer `a` that `mc-calc` is active and will return to this buffer
- in all other buffers, that `mc-calc` is active

Additional thoughts:
- The minor mode indicator could copy the calc result if clicked with left mouse button.
- Copying the top element should disable the mode. If that is not desired one could keep the mode active with prefix argument.

**Comment by hatheroldev** [comment]
I'm not fully convinced that this would be necessary, or even a valid use of minor modes.
The intended workflow is to shortly switch to calc and back again to the buffer, so there should no indicator be needed to remind the user.

Having said that, a possible use case for minor modes that I could see would be to provide a host for keybindings for grabing strings and a different keybinding for copying calc top back.
However, I currently plan to keep things simple as the user might define keybindings as he sees to fit.
